### ISSUE TITLE
[REFACTOR] 검색 화면 개선

### ISSUE THREAD

**Issue by jiwon2724** [jiwon2724/ShopliveTask#31]
### 📌 내용
- 검색 화면을 개선합니다.

### 🛠️ Todo
- [x] StateFlow 하나의 함수로 관리 및 코드 개선
- [x] 미사용 리소스 제거
- [x] 코드 가독성 개선
